## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [4]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [5]:
# 1) Seu código aqui
acertos_mat = (df_mat['Qt_acertos'].sum())/24
print(f'O percentual de acerto de matemática foi de: {acertos_mat:,.2f} %')

acertos_por = (df_por['Qt_acertos'].sum())/18
print(f'O percentual de acerto de português foi de: {acertos_por:,.2f} %')

acertos_geo = (df_geo['Qt_acertos'].sum())/8
print(f'O percentual de acerto de geografia foi de: {acertos_geo:,.2f} %')

acertos_ing = (df_ing['Qt_acertos'].sum())/8
print(f'O percentual de acerto de inglês foi de: {acertos_ing:,.2f} %')

acertos_his = (df_his['Qt_acertos'].sum())/8
print(f'O percentual de acerto de história foi de: {acertos_his:,.2f} %')

acertos_fis = (df_fis['Qt_acertos'].sum())/12
print(f'O percentual de acerto de física foi de: {acertos_fis:,.2f} %')

acertos_qui = (df_qui['Qt_acertos'].sum())/12
print(f'O percentual de acerto de química foi de: {acertos_qui:,.2f} %')

O percentual de acerto de matemática foi de: 49.38 %
O percentual de acerto de português foi de: 40.17 %
O percentual de acerto de geografia foi de: 42.00 %
O percentual de acerto de inglês foi de: 47.62 %
O percentual de acerto de história foi de: 45.00 %
O percentual de acerto de física foi de: 44.33 %
O percentual de acerto de química foi de: 45.25 %

In [6]:
# 2) Seu código aqui
total_acertos = df_mat + df_por + df_geo + df_ing + df_his + df_fis + df_qui

total_acertos['Aluno'] = np.arange(1,101,1)
total_acertos[['Aluno','Qt_acertos']]

    Aluno  Qt_acertos
0       1          35
1       2          48
2       3          50
3       4          32
4       5          30
..    ...         ...
95     96          34
96     97          27
97     98          40
98     99          40
99    100          42

[100 rows x 2 columns]

In [7]:
# 3) Seu código aqui
total_acertos['Percentual_geral'] = round((total_acertos['Qt_acertos']/(24+18+8+8+8+12+12))*100,2)
total_acertos[['Aluno','Percentual_geral']]

    Aluno  Percentual_geral
0       1             38.89
1       2             53.33
2       3             55.56
3       4             35.56
4       5             33.33
..    ...               ...
95     96             37.78
96     97             30.00
97     98             44.44
98     99             44.44
99    100             46.67

[100 rows x 2 columns]

In [8]:
# 4) Seu código aqui
aprovados = total_acertos[total_acertos['Qt_acertos'] > 45]
quantidade_aprovados = len(aprovados['Aluno'])
quantidade_aprovados

31

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [9]:
# seu código aqui 1
df_mat['Aluno'] = np.arange(1,101,1)
df_fis['Aluno'] = np.arange(1,101,1)
df_qui['Aluno'] = np.arange(1,101,1)

zerou_mat = df_mat[df_mat['Qt_acertos'] == 0]
zerou_fis = df_fis[df_fis['Qt_acertos'] == 0]
zerou_qui = df_qui[df_qui['Qt_acertos'] == 0]

desclassificados = pd.concat([zerou_mat,zerou_fis,zerou_qui])
desclassificados

    Qt_acertos  Aluno
25           0     26
94           0     95
98           0     99
3            0      4
6            0      7
12           0     13
26           0     27
35           0     36
49           0     50
56           0     57
65           0     66
66           0     67
72           0     73
73           0     74
84           0     85
10           0     11
14           0     15
20           0     21
26           0     27
27           0     28
33           0     34
74           0     75
89           0     90
92           0     93

In [10]:
#2
len(desclassificados['Aluno'].unique())

23

In [11]:
#3
alunos_desclassificados = desclassificados['Aluno'].unique()
alunos_desclassificados = sorted(alunos_desclassificados)

df_geo['Aluno'] = np.arange(1,101,1)
media_geo_his = df_geo[['Aluno','Qt_acertos']]
media_geo_his = media_geo_his.rename(columns={'Qt_acertos':'Acertos_geo'})
media_geo_his['Acertos_his'] = df_his['Qt_acertos']
media_geo_his = media_geo_his.loc[media_geo_his['Aluno'].isin(alunos_desclassificados)]

media_geo = media_geo_his['Acertos_geo'].mean()
media_his = media_geo_his['Acertos_his'].mean()

print(f'A média dos alunos desclassificados em geografia foi de {media_geo:,.2f} acertos.\nJá a média em história foi de {media_his:,.2f} acertos')

A média dos alunos desclassificados em geografia foi de 3.22 acertos.
Já a média em história foi de 3.43 acertos

In [12]:
#4
df_mat['Aluno'] = np.arange(1,101,1)
df_fis['Aluno'] = np.arange(1,101,1)
df_qui['Aluno'] = np.arange(1,101,1)

classificados = pd.merge(df_mat,df_fis, on = 'Aluno')
classificados = pd.merge(classificados,df_qui, on = 'Aluno')
classificados = classificados.rename(columns={'Qt_acertos_x':'Acertos_mat'})
classificados = classificados.rename(columns={'Qt_acertos_y':'Acertos_fis'})
classificados = classificados.rename(columns={'Qt_acertos':'Acertos_qui'})
classificados = classificados[['Aluno','Acertos_mat','Acertos_fis','Acertos_qui']]

classificados = classificados[classificados['Acertos_mat'] > 0]
classificados = classificados[classificados['Acertos_fis'] > 0]
classificados = classificados[classificados['Acertos_qui'] > 0]

classificados

    Aluno  Acertos_mat  Acertos_fis  Acertos_qui
0       1            6            8            3
1       2           19           11            8
2       3           14            4            4
4       5            7            9            3
5       6           20            9            9
..    ...          ...          ...          ...
93     94           12            6            6
95     96            6            9            3
96     97            8            4            3
97     98           23            1            5
99    100           11            7            2

[77 rows x 4 columns]

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [23]:
# 1) Sua solução aqui
dados = pd.read_csv('registros de vacinacao covid ACRE.csv',sep=',')
len(dados['vacina_codigo'])

169071

In [27]:
# 2) 
len(dados['paciente_id'].unique())

120517

In [46]:
# 3) 
dados['vacina_descricao_dose'].unique()
primeira_dose = dados[dados['vacina_descricao_dose'] == '\xa0\xa0\xa0\xa01ª\xa0Dose']
len(primeira_dose['paciente_id'].unique())

119713

In [55]:
# 4) 
menores_de_idade = dados[dados['paciente_idade'] < 18]
len(menores_de_idade['paciente_id'].unique())

47

In [57]:
# 5)
len(dados['estabelecimento_razaosocial'].unique())

42

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [113]:
# 1) 
menores_de_idade = dados[dados['paciente_idade'] < 18]

estabelecimentos = menores_de_idade[['estabelecimento_valor','estabelecimento_razaosocial','estalecimento_nofantasia',
                                    'estabelecimento_municipio_codigo','estabelecimento_municipio_nome','estabelecimento_uf']]
vacinas = menores_de_idade.groupby('estabelecimento_razaosocial').count()
vacinas = vacinas.rename(columns={'document_id':'Qt_vacinas'})
vacinas = vacinas['Qt_vacinas']

estabelecimentos = pd.merge(estabelecimentos,vacinas,on='estabelecimento_razaosocial')
estabelecimentos.drop_duplicates()

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf,Qt_vacinas
0,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC,1
1,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC,4
5,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC,3
8,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC,3
11,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC,21
12,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC,21
13,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC,21
14,6917682,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC,21
18,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC,21
32,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC,8
40,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC,3
43,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC,2
45,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC,2
47,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC,4
51,5336171,SECRETARIA DE ESTADO DE SAUDE DO ACRE,HOSPITAL REGIONAL DO JURUA,120020,CRUZEIRO DO SUL,AC,1
52,6697151,MINISTERIO DA SAUDE,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS,120050,SENA MADUREIRA,AC,1
53,3323307,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE,120080,PORTO ACRE,AC,1
54,7123043,PREFEITURA MUNICIPAL DE JORDAO,SAUDE DA FAMILIA RIBEIRINHA,120032,JORDAO,AC,1

In [116]:
# 2) 
menores_de_idade.columns

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_datanascimento', 'paciente_enumsexobiologico',
       'paciente_racacor_codigo', 'paciente_racacor_valor',
       'paciente_endereco_coibgemunicipio', 'paciente_endereco_copais',
       'paciente_endereco_nmmunicipio', 'paciente_endereco_nmpais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumnacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoatendimento_codigo',
       'vacina_grupoatendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataaplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem', 'data_importacao_rnds', 'id_sistema_origem'],
      dtype='object')

In [118]:
# 3)
menores_de_idade['vacina_categoria_nome'].count()

54

In [121]:
# 4)
informacoes = ['estabelecimento_valor','estabelecimento_razaosocial','estalecimento_nofantasia',
                                    'estabelecimento_municipio_codigo','estabelecimento_municipio_nome','estabelecimento_uf']

['estabelecimento_valor',
 'estabelecimento_razaosocial',
 'estalecimento_nofantasia',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf']

In [131]:
# 5)
menores_de_idade = menores_de_idade.loc[:,['estabelecimento_valor','estabelecimento_razaosocial','estalecimento_nofantasia',
                                    'estabelecimento_municipio_codigo','estabelecimento_municipio_nome','estabelecimento_uf']]

In [132]:
#6
menores_de_idade.drop_duplicates()

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1567,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC
6250,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
9569,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
11338,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
15144,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
17153,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
18361,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC
18608,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
20204,6917682,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
21119,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
29127,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC
57405,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC
61131,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
68290,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
69882,5336171,SECRETARIA DE ESTADO DE SAUDE DO ACRE,HOSPITAL REGIONAL DO JURUA,120020,CRUZEIRO DO SUL,AC
70881,6697151,MINISTERIO DA SAUDE,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS,120050,SENA MADUREIRA,AC
101402,3323307,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE,120080,PORTO ACRE,AC
140895,7123043,PREFEITURA MUNICIPAL DE JORDAO,SAUDE DA FAMILIA RIBEIRINHA,120032,JORDAO,AC