# Livro para consulta:
- https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html
- https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html

# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [2]:
sinasc = pd.read_csv('SINASC_RO_2019.csv')
sinasc.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

In [17]:
sinasc.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')

# Tarefa 1

### 1. Idade media das mães e dos pais por município (coluna munResNome)

In [16]:
sinasc2 = sinasc[['munResNome','IDADEMAE','IDADEPAI']]
sinasc2.groupby(['munResNome']).mean().round()

                           IDADEMAE  IDADEPAI
munResNome
Alta Floresta D'Oeste          26.0      30.0
Alto Alegre dos Parecis        25.0      29.0
Alto Paraíso                   25.0      29.0
Alvorada D'Oeste               26.0      31.0
Ariquemes                      26.0      32.0
Buritis                        26.0      31.0
Cabixi                         26.0      34.0
Cacaulândia                    26.0      36.0
Cacoal                         27.0      31.0
Campo Novo de Rondônia         25.0      30.0
Candeias do Jamari             25.0      30.0
Castanheiras                   27.0      30.0
Cerejeiras                     27.0      32.0
Chupinguaia                    25.0      30.0
Colorado do Oeste              28.0      34.0
Corumbiara                     25.0      32.0
Costa Marques                  24.0      31.0
Cujubim                        24.0      31.0
Espigão D'Oeste                26.0      31.0
Governador Jorge Teixeira      24.0      29.0
Guajará-Mirim                  25.0      30.0
Itapuã do Oeste                26.0      42.0
Jaru                           26.0      32.0
Ji-Paraná                      26.0      31.0
Machadinho D'Oeste             25.0      31.0
Ministro Andreazza             28.0      34.0
Mirante da Serra               26.0      32.0
Monte Negro                    26.0      35.0
Município ignorado - RO        24.0      22.0
Nova Brasilândia D'Oeste       26.0      31.0
Nova Mamoré                    25.0      32.0
Nova União                     27.0      31.0
Novo Horizonte do Oeste        27.0      32.0
Ouro Preto do Oeste            26.0      31.0
Parecis                        26.0      32.0
Pimenta Bueno                  25.0      30.0
Pimenteiras do Oeste           25.0      36.0
Porto Velho                    26.0      32.0
Presidente Médici              26.0      30.0
Primavera de Rondônia          27.0      32.0
Rio Crespo                     27.0      28.0
Rolim de Moura                 27.0      30.0
Santa Luzia D'Oeste            26.0      31.0
Seringueiras                   25.0      30.0
São Felipe D'Oeste             26.0      31.0
São Francisco do Guaporé       26.0      32.0
São Miguel do Guaporé          26.0      33.0
Teixeirópolis                  26.0      32.0
Theobroma                      26.0      30.0
Urupá                          27.0      31.0
Vale do Anari                  26.0      34.0
Vale do Paraíso                26.0      30.0
Vilhena                        26.0      34.0

### 2. Peso médio dos bebes por sexo que nasceram no dia do seu aniversário por faixas de escolaridade mae
Ex: Você, aluna(o), nasceu no dia 10/01, então você precisa filtrar o conjunto de dados nessa data e calcular o peso médio dos bebês de cada sexo por faixa de escolaridade da mãe.

In [64]:
sinasc3 = sinasc.loc[sinasc['DTNASC'] == '2019-04-13']
sinasc3 = sinasc3[['ESCMAE','SEXO','PESO']]
sinasc3.set_index('ESCMAE', inplace=True)
sinasc3.groupby(['ESCMAE','SEXO']).mean().round(2).unstack()

                    PESO
SEXO            Feminino Masculino
ESCMAE
1 a 3 anos       3900.00   2995.00
12 anos ou mais  3239.00   3600.00
4 a 7 anos       3268.33   3701.67
8 a 11 anos      3168.39   3466.07
Nenhuma          3770.00       NaN

### 3. Qual o municipio que nasceu menos bebe em 2019?
    - qual a idade media, maxima, minima das maes nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [83]:
sinasc.groupby(['munResNome'])['PARTO'].count().sort_values().head(2)

munResNome
Município ignorado - RO     1
Castanheiras               32
Name: PARTO, dtype: int64

In [101]:
sinasc4 = sinasc.loc[sinasc['munResNome']=='Castanheiras']
sinasc4 = sinasc4[['munResNome','IDADEMAE','IDADEPAI']]
sinasc4.groupby(['munResNome']).aggregate([('média','mean'),('idade máxima',max),('idade mínima',min)]).round()

             IDADEMAE                           IDADEPAI               \
                média idade máxima idade mínima    média idade máxima
munResNome
Castanheiras     27.0           39           17     30.0         43.0


             idade mínima
munResNome
Castanheiras         17.0

### 4. Qual o municipio que nasceu mais bebe no mês de março?
    - qual a quantidade de filhos vivos media, maxima, minima nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [84]:
sinasc.groupby(['munResNome'])['PARTO'].count().sort_values(ascending=False).head(1)

munResNome
Porto Velho    8412
Name: PARTO, dtype: int64

In [102]:
sinasc4 = sinasc.loc[sinasc['munResNome']=='Porto Velho']
sinasc4 = sinasc4[['munResNome','IDADEMAE','IDADEPAI']]
sinasc4.groupby(['munResNome']).aggregate([('média','mean'),('idade máxima',max),('idade mínima',min)]).round()

            IDADEMAE                           IDADEPAI               \
               média idade máxima idade mínima    média idade máxima
munResNome
Porto Velho     26.0           47           12     32.0         65.0


            idade mínima
munResNome
Porto Velho         16.0

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados. Algo que você julgue relevante e novo pra você.

1- Curiosamente, para mães com o menor grau de escolaridade (1 a 3 anos) as bebês do sexo feminino possuem um peso médio superior aos bebês de sexo masculino, o que é diferente para a média geral e para as demais classificações de escolaridade da mãe.

2- Ao analisar os dados de idade de pais e mães em Porto Velho, capital de RO, percebe-se que existem paternidades de indivíduos mais velhos se comparado a uma cidade mais interiorana como Castanheiras. Isso pode ser explicado pelo maior desenvolvimento de Porto Velho e o oferecimento de melhores condições de gestação às mulheres mais velhas.